name: "commit"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

  # Allows triggering the workflow manually in github actions page.
  workflow_dispatch:

defaults:
  run: # use bash for all operating systems unless overridden
    shell: bash

jobs:
  build:
    name: build
    outputs: # allows to refer it as ${{ needs.build.outputs.version }} in subsequent jobs.
      version: ${{ steps.describe.outputs.version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90 # instead of 360 by default.
    strategy:
      fail-fast: false # don't fail fast as sometimes failures are operating system specific
      matrix:
        os:
          - "ubuntu-20.04"
          - "macos-11"
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: commit-${{ runner.os }}-go-${{ hashFiles('Tools.mk') }}
          restore-keys: commit-${{ runner.os }}-go-
      - uses: actions/cache@v2
        with:
          path: ./.cache/bazel
          key: commit-${{ runner.os }}-bazel-${{ hashFiles('Tools.mk', '.bazelversion', 'bazel/repositories.bzl') }}
          restore-keys: commit-${{ runner.os }}-bazel-
      - uses: actions/cache@v2
        with:
          path: ./.cache/tools
          key: commit-${{ runner.os }}-tools-${{ hashFiles('Tools.mk') }}
      - run: sudo apt-get update && sudo apt-get -y install make cmake ninja-build build-essential
        if: runner.os == 'Linux'
      - run: brew install cmake ninja coreutils
        if: runner.os == 'macOS'
      - name: Run git describe
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Run set version
        run: echo ::set-output name=version::$(git describe --tags --abbrev=0)
        id: describe # Will be referenced as one of this job's outputs. See: "outputs" above.
      - run: make dist
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  release:
    name: release
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    runs-on: ubuntu-20.04
    timeout-minutes: 90 # instead of 360 by default.
    steps:
      - uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/download-artifact@v2
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ github.token }}
          tag: ${{ needs.build.outputs.version }}
          name: ${{ needs.build.outputs.version }}
          gzip: false
          allow_override: true
          files: |
            dist/auth_server_${{ needs.build.outputs.version }}_darwin_amd64.tar.gz
            dist/auth_server_${{ needs.build.outputs.version }}_linux_amd64.tar.gz
