name: "release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+**"  # For example: v0.2.0 v0.2.1-rc2

defaults:
  run: # use bash for all operating systems unless overridden.
    shell: bash

jobs:
  make-dist:
    name: "Make artifacts"
    outputs: # allows to refer it as ${{ needs.build.outputs.version }} in subsequent jobs.
      version: ${{ steps.describe.outputs.version }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90 # instead of 360 by default.
    strategy:
      fail-fast: false # don't fail fast as sometimes failures are operating system specific
      matrix:
        os:
          - "ubuntu-20.04"
          - "macos-11"
    steps:
      - name: Cancel when duplicated
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2 # shallow checkout.

      - name: Setup Go
        uses: actions/setup-go@v2 # prepare Go. This is required for tools.
        with:
          go-version: 1.17.x

      - name: Download cache for Go
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('Tools.mk') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Download cache for Bazel
        uses: actions/cache@v2
        with:
          path: ./.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('Tools.mk', '.bazelversion', 'bazel/repositories.bzl') }}
          restore-keys: ${{ runner.os }}-bazel-

      - name: Download cache for tools
        uses: actions/cache@v2
        with:
          path: ./.cache/tools
          key: ${{ runner.os }}-tools-${{ hashFiles('Tools.mk') }}

      - name: Run tests
        run: make test

      - name: Create artifacts
        run: ${GITHUB_REF#refs/tags/v} make dist
        env:

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-${{ runner.os }}
          path: dist

  release:
    name: release
    runs-on: ubuntu-20.04
    timeout-minutes: 90 # instead of 360 by default.
    steps:
      - name: Cancel when duplicated
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Download artifacts # get all of the uploaded artifacts
        uses: actions/download-artifact@v2

      - name: Release downloaded artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build-Linux/**/*.tar.gz
            build-macOS/**/*.tar.gz
